# Generated by Django 5.1.3 on 2025-03-09 02:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_layout_widgetpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetpreference',
            name='widget_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='widgetpreference',
            name='widget_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
