services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/staticfiles
    depends_on:
      - db
    env_file: 
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}     
      POSTGRES_USER: ${POSTGRES_USER}     
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data: 