# Generated by Django 5.1.5 on 2025-02-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_widget_archived_alter_widget_user_archivedwidget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedWidget',
        ),
    ]
