# Generated by Django 5.1.5 on 2025-02-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_archivedwidget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='title',
        ),
        migrations.AddField(
            model_name='widget',
            name='position',
            field=models.JSONField(default=dict),
        ),
    ]
